name: 'instagram_business_source_integration_tests'
version: '0.1.0'
profile: 'integration_tests'
config-version: 2

vars:
  media_history: "{{ ref('instagram_business_media_history_data') }}"
  media_insights: "{{ ref('instagram_business_media_insights_data') }}"
  user_history: "{{ ref('instagram_business_user_history_data') }}"

seeds:
  instagram_business_source_integration_tests:
    instagram_business_media_history_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}" 
        ig_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        user_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}" 
        carousel_album_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}" 
    instagram_business_media_insights_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}" 
    instagram_business_user_history_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}" 
        ig_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        

